Add support for bundled rootfs and data tarballs
Add defaults for their location in /installer,
and add checks for the existence of the tarballs
prior to starting the install.

Also work in a few other miscellaneous improvements.

Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/lib/tools-common.in b/lib/tools-common.in
--- a/lib/tools-common.in
+++ b/lib/tools-common.in
@@ -46,14 +46,6 @@ identify_platform_setup() {
 	    exit 1
 	fi
     fi
-    if [ "$INITIAL_SETUP" = "yes" ]; then
-	INSTALLTO="0 1"
-    elif [ "$curslot" != "0" -a "$curslot" != "1" ]; then
-	echo "ERR: could not identify installation partition" >&2
-	exit 1
-    else
-	INSTALLTO=$(expr 1 - $curslot)
-    fi
 
     while read -a ARGS; do
 	eval ${ARGS[@]}
@@ -90,9 +82,21 @@ identify_platform_setup() {
 		ROOTFSPART[1]="${NAME#${PKNAME}}"
 	    elif [ "$PARTLABEL" = "UDA" -o "$PARTLABEL" = "DATA" ]; then
 		DATAPART="${NAME#${PKNAME}}"
+	    elif [ "$PARTLABEL" = "INSTALLER" ]; then
+		INITIAL_SETUP=yes
 	    fi
 	fi
     done < <(lsblk -P -o MOUNTPOINT,NAME,PKNAME,PARTLABEL,TYPE)
+
+    if [ "$INITIAL_SETUP" = "yes" ]; then
+	INSTALLTO="0 1"
+    elif [ "$curslot" != "0" -a "$curslot" != "1" ]; then
+	echo "ERR: could not identify installation partition" >&2
+	exit 1
+    else
+	INSTALLTO=$(expr 1 - $curslot)
+    fi
+
     if [ "$DATAPART" = "TBD" -a "$INITIAL_SETUP" != "yes" ]; then
 	echo "ERR: no DATA partition found" >&2
 	exit 1
@@ -238,6 +242,13 @@ install_rootfs() {
         rc=1
     fi
     sync
+    if [ -z "$INSTALLED_ARTIFACT" ]; then
+	if [ -e $mptemp/etc/mender/artifact_info ]; then
+	    INSTALLED_ARTIFACT=`cut -d= -f2 $mptemp/etc/mender/artifact_info`
+	else
+	    INSTALLED_ARTIFACT=$(. $mptemp/etc/os-release 2>/dev/null; echo $PRETTY_NAME)
+	fi
+    fi
     for i in 1 2 3; do
 	if umount $mptemp 2>/dev/null; then
 	    rmdir $mptemp
@@ -410,17 +421,46 @@ update_bootloader() {
     local fs rc d
     local mounts=(/dev /sys /run /usr/bin /usr/lib /lib)
 
+    rc=0
     if [ "$INITIAL_SETUP" = "yes" ]; then
-	if ! tegra-bootloader-update --initialize "$1/opt/ota_package/bl_update_payload"; then
-	    return 1
+	if [ -e "$1/etc/nv_boot_control.template" ]; then
+	    tmpconf=`mktemp /tmp/bootctrl.XXXXXX`
+	    local boardspec=$(tegra-boardspec 2>/dev/null)
+	    local devtype=$(cat "$1/etc/hostname")
+	    if [ -z "$boardspec" ]; then
+		echo "ERR: cannot retrieve boardspec for nv_boot_control.conf generation" >&2
+		return 1
+	    fi
+	    sed -e"s,@TNSPEC@,${boardspec}-${devtype}-mmcblk0p1," $1/etc/nv_boot_control.template > "$tmpconf"
+	    export NV_BOOT_CONTROL="$tmpconf"
+	elif [ -e "$1/etc/nv_boot_control.conf" ]; then
+	    export NV_BOOT_CONTROL="$1/etc/nv_boot_control.conf"
 	fi
-	return 0
+	if ! tegra-bootloader-update --initialize "$1/opt/ota_package/bl_update_payload"; then
+	    rc=1
+	fi
+	unset NV_BOOT_CONTROL
+	[ -z "$tmpconf" ] || rm -f "$tmpconf"
+	return $rc
+    else
+	if mountpoint -q /var/lib; then
+	    mounts[${#mounts[@]}]="/var/lib"
+	else
+	    local boardspec=$(tegra-boardspec 2>/dev/null)
+	    local devtype=$(cat "$1/etc/hostname")
+	    local dest=$(readlink -f "$1/etc/nv_boot_control.conf" 2>/dev/null)
+	    if [ -z "$boardspec" ]; then
+		echo "ERR: cannot retrieve boardspec for nv_boot_control.conf generation" >&2
+		return 1
+	    fi
+	    [ -n "$dest" ] || dest="/etc/nv_boot_control.conf"
+	    sed -e"s,@TNSPEC@,${boardspec}-${devtype}-mmcblk0p1," $1/etc/nv_boot_control.template > "${1}${dest}"
+	fi
     fi
     mount -t proc proc "$1/proc"
     for fs in ${mounts[@]}; do
 	mount --bind $fs "$1$fs"
     done
-    rc=0
     if ! chroot "$1" /usr/sbin/nv_update_engine --install no-reboot 2>&1 >"$updlog"; then
 	echo "ERR: nv_update_engine failed, log follows:" >&2
 	cat "$updlog" >&2
@@ -716,5 +756,51 @@ install_machine_id() {
     rm -f "$midtmp"
     umount "$mptemp"
     rmdir "$mptemp"
+    return 0
+}
+
+# set_url
+#
+# Validate a URL for accessibility
+#
+set_url() {
+    local varname="$1"
+    local value="$2"
+    local default="$3"
+    local disposition="${4:required}"
+    local rc=0
+
+    eval $varname=""
+
+    if [ -z "$value" ]; then
+	if [ -n "$default" ]; then
+	    value="$default"
+	else
+	    if [ "$dispostion" = "required" ]; then
+		echo "ERR: missing required parameter $varname" >&2
+		return 1
+	    fi
+	fi
+    fi
+    [ -n "$value" ] || return 0
+
+    if [ "${value:0:7}" = "file://" ]; then
+	value="${value:7}"
+    fi
+    if ! echo "$value" | grep -q "://"; then
+	if [ ! -e "$value" ]; then
+	    rc=1
+	fi
+    elif ! curl --output /dev/null --silent --fail -r 0-0 "$value"; then
+	rc=$?
+    fi
+    if [ $rc -ne 0 ]; then
+	if [ "$disposition" = "required" ]; then
+	    echo "$value: invalid or not found" >&2
+	    return 1
+	fi
+	value=
+    fi
+    eval $varname="$value"
     return 0
 }
diff --git a/src/tegra-sysinstall.in b/src/tegra-sysinstall.in
--- a/src/tegra-sysinstall.in
+++ b/src/tegra-sysinstall.in
@@ -6,7 +6,6 @@
 #
 # Copyright (c) 2019, 2020 Matthew Madison
 
-INITIAL_SETUP=yes
 BOOTLOADER_UPDATES_SUPPORTED=yes
 INSTDIRTOP="/data"
 [ -d "$INSTDIRTOP" ] || mkdir -p "$INSTDIRTOP"
@@ -18,31 +17,69 @@ cleanup_and_exit() {
 	rm -rf "$INSTDIR"
     fi
     unmount_storage_partitions
-    exit $1
+    [ -z "$1" ] || exit $1
 }
 
-if [ -z "$1" ]; then
-	echo "Missing URL argument for rootfs"
-	exit 1
+usage() {
+    cat <<EOF
+Usage: `basename "$0"` [OPTION]... [ROOTFS-URI] [DATA-URI]
+Set up filesystems and install a production OS.
+
+Parameters:
+  ROOTFS-URI        location of rootfs tarball
+                    (default: /installer/image.tar.gz)
+  DATA-URI          location of data partition tarball
+                    (default: /installer/data.tar.gz, optional)
+
+Options:
+  -h, --help        displays this usage information
+
+EOF
+}
+
+ARGS=$(getopt -n $(basename "$0") -l "help" -o "h" -- "$@")
+if [ $? -ne 0 ]; then
+    echo "Error parsing command line" >&2
+    exit 1
 fi
-URL="$1"
+eval set -- "$ARGS"
+
+while true; do
+    case "$1" in
+	--help|-h)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    shift
+	    break
+	    ;;
+	*)
+	    echo "Error processing command line" >&2
+	    usage
+	    exit 1
+	    ;;
+    esac
+done
+
+set_url URL "$1" "file:///installer/image.tar.gz" || exit 1
+set_url DATA_URL "$2" "file:///installer/data.tar.gz" optional || exit 1
 
 verify_device_availability || exit 1
 
-initialize_devices || exit 1
-
-format_partitions || exit 1
-
-mount_storage_partitions || exit 1
-
-program_machine_id || exit 1
+if [ "$INITIAL_SETUP" = "yes" ]; then
+    initialize_devices || exit 1
+    format_partitions || exit 1
+    mount_storage_partitions || exit 1
+    program_machine_id || exit 1
+fi
 
 # From here down, make sure we clean up before exiting.
 
 INSTDIR=$(mktemp -q -d "$INSTDIRTOP/fwsetup.XXXXXX")
 download_file "$URL" "$INSTDIR" ROOTFS_TARBALL || cleanup_and_exit 1
-if [ -n "$2" ]; then
-    download_file "$2" "$INSTDIR" DATA_TARBALL || cleanup_and_exit 1
+if [ -n "$DATA_URL" ]; then
+    download_file "$DATA_URL" "$INSTDIR" DATA_TARBALL || cleanup_and_exit 1
 else
     DATA_TARBALL=
 fi
@@ -54,6 +91,7 @@ if [ -n "$DATA_TARBALL" ]; then
     update_datapart /data "$INSTDIR/$DATA_TARBALL" || cleanup_and_exit 1
 fi
 
+INSTALLED_ARTIFACT=
 first_targetdev=
 for i in $INSTALLTO; do
     targetdev="/dev/${ROOTFSDEV[$i]}${ROOTFSPART[$i]}"
@@ -64,19 +102,20 @@ for i in $INSTALLTO; do
     [ -n "$first_targetdev" ] || first_targetdev="$targetdev"
 done
 
-if [ "$BOOTLOADER_UPDATES_SUPPORTED" = "yes" -a -n "$first_targetdev" ]; then
-    tmpmnt=$(mktemp -q -d /tmp/bl.XXXXXX)
-    if ! mount $first_targetdev $tmpmnt 2>/dev/null; then
-	echo "ERR: could not mount rootfs for bootloader update check" >&2
+if [ -n "$first_targetdev" ]; then
+    rmount=$(mktemp -q -d /tmp/finalstaging.root.XXXXXX)
+    if ! mount "$first_targetdev" "$rmount" 2>/dev/null; then
+	echo "ERR: could not mount rootfs for post-install operations" >&2
 	cleanup_and_exit 1
     fi
-    if [ -e $tmpmnt/opt/ota_package/bl_update_payload ]; then
+fi
+
+if [ "$BOOTLOADER_UPDATES_SUPPORTED" = "yes" -a -n "$first_targetdev" ]; then
+    if [ -e $rmount/opt/ota_package/bl_update_payload ]; then
 	bootloadertext="${BOOTLOADER_NAME:-bootloader}"
 	echo "Updating $bootloadertext..."
-	update_bootloader $tmpmnt || cleanup_and_exit 1
+	update_bootloader $rmount || cleanup_and_exit 1
     fi
-    umount $tmpmnt
-    rmdir $tmpmnt 2>/dev/null
 fi
 
 # Final staging:
@@ -85,14 +124,10 @@ fi
 dmount=$(mktemp -q -d /tmp/dstage.XXXXXX)
 if mount -L DATA $dmount 2>/dev/null ; then
     if [ -n "$first_targetdev" ]; then
-	rmount=$(mktemp -q -d /tmp/dstage2.XXXXXX)
-	mount "$first_targetdev" $rmount
 	if [ -d ${rmount}/var/lib ]; then
 	    [ -d ${dmount}/var ] || mkdir ${dmount}/var
 	    cp -a ${rmount}/var/lib ${dmount}/var/
 	fi
-	umount $rmount
-	rmdir $rmount 2>/dev/null
     fi
     [ -d ${dmount}/var/lib ] || mkdir -p ${dmount}/var/lib
     /bin/date -u "+%4Y%2m%2d%2H%2M%2S" > ${dmount}/var/lib/timestamp
@@ -103,7 +138,14 @@ else
     cleanup_and_exit 1
 fi
 
-echo "Installation complete.  Removing INSTALLER partition and rebooting..."
-remove_installer_partition
+if [ -n "$INSTALLED_ARTIFACT" ]; then
+    echo "PASS: successful installation of $INSTALLED_ARTIFACT"
+else
+    echo "PASS: successful installation"
+fi
 
-cleanup_and_exit 0
+cleanup_and_exit
+if [ "$INITIAL_SETUP" = "yes" ]; then
+    echo "Installation complete.  Removing INSTALLER partition and rebooting..."
+    remove_installer_partition
+fi
